mlir/include/mlir/Dialect/Tosa/Transforms/Passes.h
mlir/include/mlir/Dialect/Tosa/Transforms/Passes.td
mlir/include/mlir/Dialect/Tosa/Transforms/TosaFoldCommon.h
mlir/lib/Dialect/Tosa/Transforms/CMakeLists.txt
mlir/lib/Dialect/Tosa/Transforms/TosaFoldCommon.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantCast.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantRSQRT.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantReciprocal.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaLayerwiseConstantFoldPass.cpp
mlir/test/Dialect/Tosa/constant-cast-opt-disable-int-folding.mlir
mlir/test/Dialect/Tosa/constant-cast-opt.mlir

Fold casts on constant tosa tensors.
* Generalize unary op element-wise function application
* Add test

[FXML-1871] Implement folding for constant TOSA casts

---

mlir/test/Dialect/Tosa/constant-add-opt.mlir
mlir/test/Dialect/Tosa/constant-cast-opt.mlir

* fix add tests
* clean-up unnecessary splits

Fix: Add tests checked that no casts are present

---

mlir/include/mlir/Dialect/Tosa/Transforms/Passes.h
mlir/include/mlir/Dialect/Tosa/Transforms/TosaFoldCommon.h
mlir/lib/Dialect/Tosa/Transforms/CMakeLists.txt
mlir/lib/Dialect/Tosa/Transforms/TosaFoldCommon.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantClamp.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantRSQRT.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantReciprocal.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaLayerwiseConstantFoldPass.cpp
mlir/test/Dialect/Tosa/constant-clamp-opt.mlir

* Introduce global heuristic when to fold unary operators
* Add folding constant clamps + test case

[FXML-1931] Implement constant clamp folding

---

mlir/include/mlir/Dialect/PDL/IR/PDLOps.td
mlir/include/mlir/Dialect/PDLInterp/IR/PDLInterpOps.td
mlir/include/mlir/IR/PatternMatch.h
mlir/lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp
mlir/lib/Conversion/PDLToPDLInterp/Predicate.h
mlir/lib/Conversion/PDLToPDLInterp/PredicateTree.cpp
mlir/lib/IR/PatternMatch.cpp
mlir/lib/Rewrite/ByteCode.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/Conversion/PDLToPDLInterp/pdl-to-pdl-interp-matcher.mlir
mlir/test/Dialect/PDL/ops.mlir
mlir/test/Rewrite/pdl-bytecode.mlir
mlir/test/lib/Rewrite/TestPDLByteCode.cpp
mlir/test/mlir-pdll/Parser/constraint-failure.pdll
mlir/test/mlir-pdll/Parser/constraint.pdll

This PR adds support for PDLL native constraints to return results. 
This is useful for situations where a pattern checks for certain constraints of multiple interdependent attributes and computes a new attribute value based on them. Currently we do this check natively in C++ during matching and after a successful match have to escape to native C++ again to do the computation during the rewriting part of the pattern. With this PR we can do the computation in C++ during matching and use the result in the rewriting part of the pattern. Effectively this enables a choice in the trade-off of memory consumption during matching vs recomputation of values.
This is a simplified example of a situation where this is useful: We have two operations with certain attributes that have interdependent …

FXML.1923: PDLL support for native constraints with attribute results

---

mlir/include/mlir/Dialect/Tosa/Transforms/Passes.h
mlir/lib/Dialect/Tosa/Transforms/CMakeLists.txt
mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantMul.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaLayerwiseConstantFoldPass.cpp
mlir/test/Dialect/Tosa/constant-mul-opt.mlir

Implement folding for constant multiplications.
* Add tests
* Use unspecified integer overflow behavior

[FXML-1930] Implement mul folding

---

mlir/lib/Dialect/Tosa/Transforms/TosaFoldConstantAdd.cpp
mlir/test/Dialect/Tosa/constant-add-opt.mlir

* Adapt `add`
* `pow`/`sqrt`/`reciprocal`operate only on floats
* `cast` has its own definition for these cases
* `clamp` is not affected

[FXML-2019] Update existing folds to unspecified int overflow

---

mlir/include/mlir/Dialect/PDL/IR/PDLOps.td
mlir/include/mlir/Dialect/PDLInterp/IR/PDLInterpOps.td
mlir/include/mlir/Tools/PDLL/AST/Nodes.h
mlir/lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp
mlir/lib/Dialect/PDL/IR/PDL.cpp
mlir/lib/Dialect/PDLInterp/IR/PDLInterp.cpp
mlir/lib/Rewrite/ByteCode.cpp
mlir/lib/Tools/PDLL/AST/NodePrinter.cpp
mlir/lib/Tools/PDLL/AST/Nodes.cpp
mlir/lib/Tools/PDLL/CodeGen/MLIRGen.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/Conversion/PDLToPDLInterp/pdl-to-pdl-interp-rewriter.mlir
mlir/test/Dialect/PDL/ops.mlir
mlir/test/Dialect/PDLInterp/ops.mlir
mlir/test/Rewrite/pdl-bytecode.mlir
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/test/mlir-pdll/Parser/stmt-failure.pdll

This PR extends PDLL and the underlying PDL, PDL_Interp and byte code interpreter components with support for creating new operations with empty regions.
This is an initial step towards adding full support for operations with regions, i.e. generating an operation with a region and new nested ops within that region.
However, this PR already enables expressing some patterns with less (or at least more generic) native calls. 
Here is an example of creating a new operation with a region and nesting other operations into it:
Without this PR this Pattern looks like:
```
Rewrite createOpWithRegion() -> Op;
Rewrite addAttributeToOp(op: Op, attr: Attr) -> Op;
Rewrite moveOpsIntoRegion(op: Op, results: ValueRange);
Pattern op_with_region_old with benefit(3) {
let root = op<test.op>() {"attr" = …
```

FXML.2007: PDLL support for creating new ops with empty regions

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/constant-op-fold.mlir

Often times the statements between two casts which represent simple Quantize and Dequantize operations can be simplified as their zero points are zero.
```
%0 = "tosa.const"() {value = dense<0> : tensor<1x1x1x1xi8>} : () -> tensor<1x1x1x1xi8>
%1 = "tosa.cast"(%arg0) : (tensor<32x3x224x224xf32>) -> tensor<32x3x224x224xi8>
%2 = "tosa.add"(%1, %0) {OutputName = "QuantizeLinear_2"} : (tensor<32x3x224x224xi8>, tensor<1x1x1x1xi8>) -> tensor<32x3x224x224xi8>
%3 = "tosa.sub"(%2, %0) {LayerName = "DequantizeLinear_5"} : (tensor<32x3x224x224xi8>, tensor<1x1x1x1xi8>) -> tensor<32x3x224x224xi8>
%4 = "tosa.cast"(%3) : (tensor<32x3x224x224xi8>) -> tensor<32x3x224x224xf32>
```
The add and sub statements are then redundant and do no work as the constants to these operations are zero. The add and sub …

[FXML-1991] Update Add and Sub Constant Folding

---

mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/constant-op-fold.mlir

Quantization Operations in TOSA are represnted using the following operators:
```
%0 = "tosa.const"() {value = dense<3.125000e-02> : tensor<1x1x1x1xf32>} : () -> tensor<1x1x1x1xf32>
%1 = "tosa.reciprocal"(%0) : (tensor<1x1x1x1xf32>) -> tensor<32x3x224x224xf32>
%2 = "tosa.mul"(%arg0, %1) {LayerName = "QuantizeLinear_2", shift = 0 : i32} : (tensor<32x3x224x224xf32>, tensor<32x3x224x224xf32>) -> tensor<32x3x224x224xf32>
%3 = "tosa.cast"(%2) : (tensor<32x3x224x224xf32>) -> tensor<32x3x224x224xi8>
```
Here we apply the reciprocal of a constant scale factor which can be easily folded into the constant.
These changes introduce that folding to help simplify possible pattern matching later on.

[FXML-1991] Reciprocal Constant Folding For a Splat Tensor

---

mlir/lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp
mlir/lib/Rewrite/ByteCode.cpp
mlir/test/Conversion/PDLToPDLInterp/pdl-to-pdl-interp-matcher.mlir

The `PDLToPDLInterp` pass tries to fuse common checks for multiple pdl patterns as much as possible. This PR fixes a bug where the fusion of multiple `pdl.apply_native_constraint` operations with results leads to incorrect pdl_interp code. This was due to the assumption that all uses of the results of a `pdl.apply_native_constraint` operation are known before the pass starts. This assumption was wrong as the pass may introduce more uses through fusion.
[This new test](https://github.com/Xilinx/llvm-project/blob/535f8a280d1373c2e44c9de2af20c0a43a45e9e9/mlir/test/Conversion/PDLToPDLInterp/pdl-to-pdl-interp-matcher.mlir#L111) illustrates the now correct behavior.
This also fixes incorrect behavior of the bytecode interpreter in the context of constraints with results that are evaluated as …

fix fused native constraints with results

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp

This should handle both static and dynamic shapes of operations.
For now, we only support `atan2` operations, but we can add more as we discover them.
There will be another PR that handles legalization from unsupported `torch.aten` operations to `tosa.custom_op` in the `torch-mlir` repo.

Support lowering tosa.custom_op to another dialect operation.

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg.mlir

In a discussion between Liam and Martin, it came up that we don't need to open `llvm-project` every time we need to support another (element_wise) `tosa.custom_op`. 
We essentially map one-to-one the `tosa.custom_op` to a `math` operation, when attribute `implementation_attrs` is set to `linalg.generic`.

Generic support for tosa.custom_op

---

mlir/lib/Conversion/TosaToSCF/TosaToSCF.cpp
mlir/lib/Conversion/TosaToSCF/TosaToSCFPass.cpp
mlir/test/Conversion/TosaToSCF/tosa-to-scf.mlir

This is a cherry-pick of https://reviews.llvm.org/D151117.
This patch adds support for `tosa.scatter` lowering in the `--tosa-to-scf` pass. Here's an example for this lowering:
```
func.func @tosa(
%valuesIn : tensor<3x7x5xi32>,
%indices : tensor<3x6xi32>,
%input : tensor<3x6x5xi32>) ->
tensor<3x7x5xi32> {
%0 = "tosa.scatter"(%valuesIn, %indices, %input) :
(tensor<3x7x5xi32>,
tensor<3x6xi32>,
tensor<3x6x5xi32>) ->
(tensor<3x7x5xi32>)
return %0 : tensor<3x7x5xi32>
}
```
translates to
```
func.func @tosa(%arg0: tensor<3x7x5xi32>, %arg1: tensor<3x6xi32>, %arg2: tensor<3x6x5xi32>) -> tensor<3x7x5xi32> {
%c0 = arith.constant 0 : index
%c3 = arith.constant 3 : index
%c1 = arith.constant 1 : index
%c6 = arith.constant 6 : index
%c2 = arith.constant 2 : index
%c5 = arith.constant 5 : index
%c0_0 …
```

Lowering for 'tosa.scatter'

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp

It is safer to use `int64_t` than `int32_t` when converting `min` and `max` attributes from `tosa.clamp` operation.

TorchToLinAlg: fix tosa.clamp legalization for integer types.

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/mlir-tests.yml

Due to security (?) restrictions in github CI, PRs can only access the caches that were created by builds on the target branch (but not builds caused by sibiling PRs to the same target branch).
So we need to build the target branches (here: on every push, i.e. PR merge) to populate the caches.

.github/workflows/mlir-tests.yml: Build main branches to populate ccache

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/python/mlir/dialects/_pdl_ops_ext.py

The python bindings for `ApplyNativeConstraintOp` were not aware of possible results of this operation.
Now they are

fix native constraint op in mlir python bindings

---

mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
mlir/lib/Conversion/TosaToTensor/TosaToTensor.cpp
mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp

This allows to collapse sequences of reshapes during the PDLL pass.

[MLIR] [TOSA]: Move reshape(reshape(x)) -> reshape(x) from canonicalization to fold

---

llvm/cmake/modules/AddLLVM.cmake

This is important because third-party libraries like boost etc will have the SYSTEM property set by default on their include directories. This suppresses compiler warnings in their headers.
But doing
```
add_mlir_library( myLib
my.cpp
LINK_LIBS boost)
```
would `forget` the SYSTEM property on the boost include path and cause compiler warnings when building mylib.
When using warnings-as-errors, this will fail the build.

llvm/cmake/modules/AddLLVM.cmake: objlib: Preserve the SYSTEM property of include dirs of dependences

---

mlir/include/mlir/IR/OperationSupport.h
mlir/lib/IR/AsmPrinter.cpp
mlir/test/IR/mlir-newline-after-attr.mlir

For operations that have many subgraphs, it makes the IR easier to read and makes reference differences easier to understand.

MLIR: Add option to print attributes on newlines

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-sub.mlir

This is essentially a copy of the tosa.add folder

TOSA: add folder for tosa.sub

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-op-fold.mlir

This speeds up the TosaLayerwiseConstantFoldPass on an important benchmark from 86 seconds to 7 seconds.

TosaLayerwiseConstantFoldPass: speed up folding of transpose for bf16

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-pad.mlir

I stumbled upon this issue when folding a large 3D tensor. The calculation of the index when the value ISN'T a pad must come from the `inputShape`, and needs to be updated as well.
Because our LIT tests didn't catch this (mostly due to using single values), I also updated them to multiple values so that we don't miss anything.
Also tested internally with some huge tensor.

[MLIR] [TOSA]: fix input index of tosa.pad folding. Improve lit tests.

---

mlir/include/mlir/IR/BuiltinAttributes.td
mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/unittests/IR/AttributeTest.cpp

Pre-review [here](https://gitenterprise.xilinx.com/rogarcia/llvm-project/pull/2).

Add `getNonSplatRawData` method to `DenseIntOrFPElementsAttr` for fast retrieval of internal data

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-rsqrt-opt.mlir

Make sure to use the correct APFloat semantics for bfloat16. Disable folding for float16 for now, due to uncertainty about precision requirements.

[FXML-2939] Fix rsqrt folder for bfloat16

---

mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
mlir/test/Dialect/Tosa/reduce_rank5.mlir

Lift the restrictions on 4d reduce_sum. Even if this is out of spec, it's necessary in real world model.

tosa.reduce_sum: Support any rank

---

mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
mlir/lib/Dialect/Tosa/IR/TosaOps.cpp
mlir/test/Conversion/TosaToTensor/tosa-to-tensor.mlir
mlir/test/Dialect/Tosa/invalid.mlir

Added missing verifiers for concat, pad as per the tosa spec. 
A brief list of cases covered in each verifier:
- Added verify method to cover the below checks
- All inputs must have the same rank
- Axis along which concatenation is to occur, in range from 0 to rank(shape)-1
- Added new test cases in invalid.mlir to validate
- All inputs must have the same data type
- Output shape and type must match inferred shape and type
- Added InferTensorType interface to Tosa_pad. This will run verification of the inferred output types
- Added verify method to test the padding tensor
-  rank of padding tensor must be [rank(inputShape), 2]
- each element in the padding tensor must be >= 0
- Added new test cases in invalid.mlir

new tosa verifiers

---

mlir/lib/Conversion/PDLToPDLInterp/PredicateTree.cpp
mlir/test/Conversion/PDLToPDLInterp/use-constraint-result.mlir

When sorting constraints, ensure that native calls are in an order that follows their SSA dependencies.
This allows to use the results of a native constraint in another native constraint.

PDLToPDLInterp: Ensure dependencies between native constraints and their arguments

---

mlir/include/mlir/Tools/PDLL/AST/Nodes.h
mlir/lib/Tools/PDLL/AST/Nodes.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/Parser/expr-failure.pdll
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/test/mlir-pdll/Parser/stmt-failure.pdll

This allows to write `10 : i32` to mean the same as `attr<"10: i32">`.

PDLL: Parse integer literals into AttributeExpr

---

mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/Parser/expr.pdll

Allows `"value"` wherever `attr<"\"value\"">` is allowed.

PDLL: Parse string literals into AttributeExpr

---

mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/Parser/expr-failure.pdll
mlir/test/mlir-pdll/Parser/expr.pdll

Parenthesis in PDLL are parsed as tuples. This conversion allows to use parenthesis in math expressions, so that `(a +b)` can be used as expression, allowing to write `(a + b) * c`.
Support for the actual math operators will come in a follow-up PR.

PDLL: Allow to implictly convert Tuple<Attr> with a single element to Attr

---

mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yaml
mlir/test/Dialect/Linalg/generalize-named-ops.mlir

This reduces our diff with upstream. I couldn't find any commit on our side that introduced this change, so maybe it was a merge conflict issue?

Revert wrong (?) diff to upstream

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize.mlir

Allow for BF16 in the canonicalization of pow + reciprocal into rsqrt.

BF16 canonicalization of Pow + Reciprocal

---

mlir/include/mlir/Dialect/EmitC/IR/EmitCTypes.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/invalid_types.mlir
mlir/test/Dialect/EmitC/types.mlir

This models a one or multi-dimensional C/C++ array.

[EmitC] Add ArrayType (#26)

---

.github/workflows/pr-code-format.yml

The action is from upstream LLVM, but it's disabled by default on forks. This PR enables it.
This shows that the action works: https://github.com/Xilinx/llvm-project/pull/123

CI: Enable PR action to check for proper code formatting

---

mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/Parser/expr-failure.pdll

This creates precedence between expressions, preparing for all the expressions that will come later.
While doing this, I noticed that `!` has a bug when it's not followed by a function call. I added two tests and a check for that.

PDLL: Fix crash when logical not doesn't apply to call; prepare precedence

---

mlir/include/mlir-c/BuiltinAttributes.h
mlir/lib/Bindings/Python/IRAttributes.cpp
mlir/lib/CAPI/IR/BuiltinAttributes.cpp
mlir/test/python/dialects/builtin.py
mlir/test/python/ir/array_attributes.py
mlir/test/python/ir/attributes.py

We noticed when reading the attribute:
```
denseattr = dense<[1, 2, 3, 4]> : vector<4xindex>
```
the python binding code would fail:
```
DenseIntElementsAttr(op.attributes["denseattr "])
```
When converting the attribute to the dense representation. In C++ we can represent the DenseIntElementsAttr as a vector type with index elements. This PR attempts to resolve this issue for python bindings as well.

[FIX] Python Bindings DenseIntElementsAttr as Vector<? x Index> type

---

mlir/include/mlir/Dialect/EmitC/IR/EmitCTypes.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Dialect/EmitC/invalid_ops.mlir
mlir/test/Dialect/EmitC/invalid_types.mlir
mlir/test/Dialect/EmitC/types.mlir
mlir/test/Target/Cpp/declare_func.mlir
mlir/test/Target/Cpp/func.mlir
mlir/test/Target/Cpp/invalid.mlir
mlir/test/Target/Cpp/invalid_declare_variables_at_top.mlir
mlir/test/Target/Cpp/variable.mlir

This backports the PR that just landed upstream with all its review comments.

Backport: [mlir][emitc] Add ArrayType (#83386)

---

mlir/include/mlir/Dialect/LLVMIR/LLVMOps.td
mlir/include/mlir/Dialect/SPIRV/IR/SPIRVControlFlowOps.td
mlir/include/mlir/Interfaces/FunctionInterfaces.td
mlir/lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp
mlir/lib/Conversion/ControlFlowToSCF/ControlFlowToSCF.cpp
mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp
mlir/lib/Conversion/MemRefToLLVM/MemRefToLLVM.cpp
mlir/lib/Conversion/SCFToSPIRV/SCFToSPIRV.cpp
mlir/lib/Dialect/Affine/IR/AffineOps.cpp
mlir/lib/Dialect/Async/IR/Async.cpp
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp
mlir/lib/Dialect/Linalg/Transforms/DropUnitDims.cpp
mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp
mlir/lib/Dialect/Linalg/Utils/Utils.cpp
mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp
mlir/lib/Dialect/SPIRV/IR/ControlFlowOps.cpp
mlir/lib/Dialect/Shape/IR/Shape.cpp
mlir/lib/Dialect/SparseTensor/Transforms/SparseTensorRewriting.cpp
mlir/lib/Target/SPIRV/Deserialization/Deserializer.cpp

I had picked this commit when I backported all emitc commits as it was touching one of the emitc source files.
This commit breaks compatibility with our onnx-mlir fork, so we need to revert it until we bump onnx-mlir.
This reverts commit 65d0767729f47153b6cca0a5e0125b4b36bd5e57.

Revert "[mlir] Use `OpBuilder::createBlock` in op builders and patterns (#82770)"

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Target/Cpp/conditional.mlir

Backport from upstream.
This adds an `emitc.conditional` operation for the ternary conditional operator. Furthermore, this adds a converion from `arith.select` to the new op.

[mlir][EmitC] Add an `emitc.conditional` operator (#84883)

---

mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Target/Cpp/common-cpp.mlir
mlir/test/Target/Cpp/const.mlir
mlir/test/Target/Cpp/for.mlir
mlir/test/Target/Cpp/stdops.mlir

instead of emitting a double precision literal plus a cast. This helps consumers of the emitted code when there are large numbers of floating point literals.

TranslateToCpp: Emit floating point literals with suffix

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

Does not include integer divison, because there are ops for unsigned and signed integer division.

ArithToEmitC: Handle addi, subi and muli

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/include/mlir/Dialect/EmitC/IR/EmitCTypes.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/invalid_ops.mlir

Restrict which integers types and floating point types are valid in EmitC. This should cover the types which are supported in C++ and is aligned with what the emitter currently supports.

[FXML-4320][mlir][emitc] Restrict integer and float types

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/include/mlir/Dialect/EmitC/IR/EmitCTypes.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/invalid_types.mlir

Use what is currently supported by the emitter to restrict the valid types of EmitC operations. Define utility function for valid types, such that they can be used to restrict the operations in the table gen as well as being available for reuse in dialect conversions.

[FXML-4320] Restrict types that are valid in EmitC

---

mlir/include/mlir/Dialect/Tosa/Utils/ConversionUtils.h
mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/lib/Dialect/Tosa/Utils/ConversionUtils.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg-invalid.mlir
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg.mlir

Lowering tosa.clamp with unsigned integer element types needs to use `cmpi ult` instead of `cmpi slt`,
and the lower/upper bound must be interpreted as unsigned when converting to to arith.constants.

TosaToLinalg: Fix unsigned tosa.clamp

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc-cast-truncate.mlir
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

This PR fixes the behavior of int-to-float conversions, by issuing an explicit cast to signed or unsigned when the source type (in MLIR) is a signless integer. Thanks @josel-amd for pointing this out!

[FXML-4281] Fix signedness behavior of unsigned integer <-> floating-point conversions

---

mlir/include/mlir/Dialect/Math/Transforms/Passes.h
mlir/lib/Dialect/Math/Transforms/ExpandPatterns.cpp
mlir/test/Dialect/Math/expand-math.mlir
mlir/test/lib/Dialect/Math/TestExpandMath.cpp

This PR adds support for Rsqrt lowering by expanding it into fdiv(1, sqrt(a)). This is how MathToLLVM does it (see https://github.com/llvm/llvm-project/blob/f2ade91a9fe7c222ea919748d30b74397911ecc8/mlir/lib/Conversion/MathToLLVM/MathToLLVM.cpp#L227).

[FXML-4419] Lower rsqrt to sqrt + fdiv

---

mlir/include/mlir/Dialect/Bufferization/IR/Bufferization.h
mlir/lib/Dialect/Bufferization/IR/BufferizationOps.cpp
mlir/lib/Dialect/Bufferization/Transforms/Bufferize.cpp
mlir/test/Dialect/Bufferization/Transforms/finalizing-bufferize.mlir
mlir/test/Dialect/Bufferization/Transforms/one-shot-module-bufferize-out-params.mlir
mlir/test/Dialect/Bufferization/Transforms/one-shot-module-bufferize.mlir
mlir/test/Dialect/Bufferization/canonicalize.mlir

This allows to configure both the op used for allocation and copy of memrefs.
It also changes the default behavior because the default allocation in `BufferizationOptions` creates `memref.alloc` with `alignment = 64` where we used to create `memref.alloca` without any alignment before.

[mlir][Bufferization] castOrReallocMemRefValue: Use BufferizationOptions (FXML-4352)

---

llvm/include/llvm/Support/Casting.h
llvm/unittests/Support/Casting.cpp
mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/include/mlir/Target/Cpp/CppEmitter.h
mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/lib/Conversion/ArithToEmitC/ArithToEmitCPass.cpp
mlir/lib/Conversion/FuncToEmitC/FuncToEmitCPass.cpp
mlir/lib/Conversion/MemRefToEmitC/MemRefToEmitC.cpp
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/lib/Dialect/EmitC/Transforms/FormExpressions.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc-failed.mlir
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir
mlir/test/Conversion/MemRefToEmitC/memref-to-emitc.mlir
mlir/test/Dialect/EmitC/invalid_ops.mlir
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Dialect/EmitC/transforms.mlir
mlir/test/Target/Cpp/global.mlir
mlir/test/Target/Cpp/subscript.mlir

Backported all emitc-related commits from upstream
```
git log ..upstream/main -- \
mlir/include/mlir/Dialect/EmitC \
mlir/include/mlir/Target/Cpp \
mlir/lib/Conversion/ArithToEmitC \
mlir/lib/Conversion/FuncToEmitC \
mlir/lib/Conversion/MemRefToEmitC \
mlir/lib/Conversion/SCFToEmitC \
mlir/lib/Dialect/EmitC \
mlir/lib/Target/Cpp \
mlir/test/Conversion/ArithToEmitC \
mlir/test/Conversion/FuncToEmitC \
mlir/test/Conversion/MemRefToEmitC \
mlir/test/Conversion/SCFToEmitC \
mlir/test/Dialect/EmitC \
mlir/test/Target/Cpp
```
fyi @TinaAMD

Backported all emitc-related commits from upstream

---

mlir/lib/Dialect/Arith/Transforms/ExpandOps.cpp
mlir/test/Dialect/Arith/expand-ops.mlir

Since the last LLVM bump, arith gained new ops minsi, maxsi, minui and maxui, which are used by some tosa-to-linalg lowerings.
Expand them into cmp + select to be able to lower into emitc.

expand-ops: minsi/maxsi (and unsigned)

---

mlir/include/mlir/Conversion/TosaToLinalg/TosaToLinalg.h
mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/lib/Conversion/TosaToLinalg/TosaToLinalgNamed.cpp
mlir/lib/Conversion/TosaToLinalg/TosaToLinalgNamedPass.cpp
mlir/lib/Conversion/TosaToLinalg/TosaToLinalgPass.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg-named.mlir

This PR allows to lower unsigned `tosa.max_pool2d` to linalg.
```
// CHECK-LABEL: @max_pool_ui8
func.func @max_pool_ui8(%arg0: tensor<1x6x34x62xui8>) -> tensor<1x4x32x62xui8> {
// CHECK: builtin.unrealized_conversion_cast {{.*}} : tensor<1x6x34x62xui8> to tensor<1x6x34x62xi8>
// CHECK: arith.constant 0
// CHECK: linalg.pooling_nhwc_max_unsigned {{.*}} : (tensor<1x4x32x62xi8>) -> tensor<1x4x32x62xi8>
// CHECK: builtin.unrealized_conversion_cast {{.*}} : tensor<1x4x32x62xi8> to tensor<1x4x32x62xui8>
%0 = tosa.max_pool2d %arg0 {pad = array<i64: 0, 0, 0, 0>, kernel = array<i64: 3, 3>, stride = array<i64: 1, 1>} : (tensor<1x6x34x62xui8>) -> tensor<1x4x32x62xui8>
return %0 : tensor<1x4x32x62xui8>
}
```
It does this by
1) Moving the type converter from …

TosaToLinalg: Support unsigned tosa.max_pool2d (FXML-4556)

---

mlir/include/mlir/Dialect/PDL/IR/Builtins.h
mlir/lib/Dialect/PDL/IR/Builtins.cpp
mlir/lib/Tools/PDLL/Parser/Lexer.cpp
mlir/lib/Tools/PDLL/Parser/Lexer.h
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll-lsp-server/completion.test
mlir/test/mlir-pdll/CodeGen/MLIR/expr.pdll
mlir/test/mlir-pdll/Parser/expr-failure.pdll
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/unittests/Dialect/PDL/BuiltinTest.cpp

PDLL native operator abs (use case in flexml: https://gitenterprise.xilinx.com/FaaSApps/vitis_flexml/blob/78229fda971cc942e06d78867c864f877b1437e9/data/Transform/pdll/shared/native_calls.pdll#L89) and some code refactor in `Builtins.cpp` and `Builtins.h`

PDLL native operator abs

---

mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
mlir/include/mlir/Dialect/Tosa/IR/TosaTypesBase.td
mlir/lib/Dialect/Tosa/Transforms/TosaValidation.cpp
mlir/test/Dialect/Tosa/invalid.mlir
mlir/test/Dialect/Tosa/level_check.mlir

This backports `[TOSA] Allow all integer types in most ops` from upstream
and on top also allows all floating point types (notably f64 and various 8-bit float types).

[mlir] [TOSA] Allow any floating point type

---

mlir/include/mlir/Conversion/TosaToTensor/TosaToTensor.h
mlir/lib/Conversion/TosaToTensor/TosaToTensor.cpp
mlir/lib/Conversion/TosaToTensor/TosaToTensorPass.cpp
mlir/test/Conversion/TosaToTensor/tosa-to-tensor.mlir

Update the conversion for tosa.reshape to properly use the type converter, so tosa.reshape on unsigned types work.

TosaToTensor: Support reshape on unsigned

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-cos.mlir
mlir/test/Dialect/Tosa/constant-sin.mlir

https://github.com/Xilinx/llvm-project/pull/178 closed. Same, reverting the format completely is easier in this way.
`tosa.sin` and `tosa.cos` support only `bf16`, `f16`, and `f32`.

[Tosa] support sin/cos constant fold

---

mlir/include/mlir/Dialect/Tosa/Transforms/Passes.h
mlir/include/mlir/Dialect/Tosa/Transforms/Passes.td
mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/lib/Dialect/Tosa/Transforms/TosaLayerwiseConstantFoldPass.cpp
mlir/test/Dialect/Tosa/constant-tile.mlir

Constant fold `tosa.tile` when `enable-tile-folding=true` is passed as option.
Tests results were generated using `pytorch`:
```
import torch
torch.set_printoptions(sci_mode=True, precision=6)
x = torch.tensor([1, 2, 3])
print(x)
print(x.tile((2,)))
x = torch.tensor([[[[True]],[[False]],[[True]]]])
print(x)
print(x.tile((1,1,2,3)))
x = torch.tensor([[[[0.25, 0.125]],[[0.5, 1.0]],[[2.0, 4.0]]]], dtype=torch.bfloat16)
print(x)
print(x.tile((1,1,2,1)))
x = torch.tensor([[0.25, 1.25], [2.25, 3.25]])
print(x)
print(torch.tile(x, (2, 2)))
x = torch.tensor([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])
print(x)
print(torch.tile(x, (2, 2, 2)))
x = torch.tensor([[[1.0]], [[2.0]], [[3.0]]], dtype=torch.float16)
print(x)
print(torch.tile(x, (2, 2, 2)))
```

feat: constant fold tosa.tile.

---

mlir/lib/Dialect/Tosa/Transforms/TosaFolders.cpp
mlir/test/Dialect/Tosa/constant-tile.mlir

There was one case missing : when the input is a splat. Now we should cover all cases.

feat: constant fold tosa.tile when input is splat.

---

mlir/include/mlir/IR/PatternMatch.h
mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize_with_debuginfo.mlir

During Tosa Clamp folding the location information of one of the clamps was being lost due to the newly created operation simply taking only a single location rather than the fused location. 
The following fix extends the replaceOpWithNewOp to allow the user to give a list of locations so that a FusedLoc can be created on the newly generated operation.

fix(TosaCanonicalize): create FusedLoc when folding clamp

---

mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Target/Cpp/for.mlir

`emitc.size_t` is the default type in emitc::ForLoop induction variables now, so the type is not printed in the MLIR "assembly". However, index type is still assumed at parse time barring further type information in the IR. This commit reconciles the print and parse behavior to assume `emitc.size_t` as the default type.

Fix discrepancy in EmitC parser/printer

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

I was preparing the cmpf upstream PR an noticed we were missing `ole`. Since the switch now covers all cases, there was a warning that the default cannot be triggered, so I am pretty confident it is now complete 😄

Add missing cmpf conversion

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

Convert `arith.negf` to `emitc.unary_minus`. Did not see any special cases here, so use a straight forward translation.

[mlir][emitc] Implement arith.negf to EmitC

---

mlir/include/mlir/Conversion/TosaToArith/TosaToArith.h
mlir/lib/Conversion/TosaToArith/TosaToArith.cpp
mlir/lib/Conversion/TosaToArith/TosaToArithPass.cpp
mlir/test/Conversion/TosaToArith/tosa-to-arith.mlir

To ensure that ui8 consts become i8 in arith

TosaToArith: Use type converter for tosa.const

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/constant-op-fold.mlir

It appears the [TOSA reference model](https://git.mlplatform.org/tosa/reference_model.git/commit/?id=57bc0796cd85115684219cf373db04c172848306) as well as the rest of the source tree here uses roundeven for float-to-int conversions. Folding of `tosa.cast` ops with constant "splat" input was an exception, that this PR eliminates.
One approval will be sufficient for this small patch.

[FXML-4732] Fix TOSA cast constant op folding

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize_with_debuginfo.mlir

feat: Create a fused location for rsqrt canonicalization

---

mlir/include/mlir-c/IR.h
mlir/lib/Bindings/Python/IRCore.cpp
mlir/lib/Bindings/Python/IRModule.h
mlir/lib/CAPI/IR/IR.cpp
mlir/python/mlir/_mlir_libs/_mlir/ir.pyi
mlir/test/CAPI/ir.c
mlir/test/python/ir/operation.py

The MLIR C and Python Bindings expose various methods from `mlir::OpPrintingFlags` . This PR adds a binding for the `skipRegions` method, which allows to skip the printing of Regions when printing Ops. It also exposes this option as parameter in the python `get_asm` and `print` methods

Expose skipRegions option for Op printing in the C and Python bindings

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg.mlir

In lowering a tosa.cast op from float to signed int, the float is compared against INT_MAX to check for overflow. The 1 + INT_MAX(width) constant is converted to floating-point, and comparison with it is done in FP. 
However, an intermediate `int64_t` type is used, which overflows and turns 1 + INT_MAX(64) negative when the destination type is `i64`. This PR uses `uint64_t` instead (with `getZExtValue`) so that 1 + INT_MAX stays in bounds and is correctly represented as floating-point.

[FXML-4770] TosaToLinalg: fix tosa.cast INT_MAX overflow constant

---

mlir/include/mlir/Tools/PDLL/Parser/Parser.h
mlir/lib/Tools/PDLL/Parser/Lexer.cpp
mlir/lib/Tools/PDLL/Parser/Lexer.h
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/lib/Tools/mlir-pdll-lsp-server/PDLLServer.cpp
mlir/test/mlir-pdll/Parser/include-file-and-file-which-includes-first-file-with-once-00.pdll
mlir/test/mlir-pdll/Parser/include-file-and-file-which-includes-first-file-with-once-01.pdll
mlir/test/mlir-pdll/Parser/include-file-twice-with-once.pdll
mlir/test/mlir-pdll/Parser/include-file-twice-without-once.pdll
mlir/test/mlir-pdll/Parser/include/include-file-with-include.pdll
mlir/test/mlir-pdll/Parser/include/included-with-once.pdll
mlir/tools/mlir-pdll/mlir-pdll.cpp

This eases developing .pdll files with the help of `mlir-pdll-lsp-server`

Allow to specify `#once` on .pdll to enable better modular "header" inclusion 

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

This is pretty straightforward now that we have a sign & type conversion framework in ArithToEmitC.

[FXML-4643] Lower arith.divui to EmitC

---

mlir/lib/Dialect/PDL/IR/Builtins.cpp
mlir/unittests/Dialect/PDL/BuiltinTest.cpp

Until now log2 was returning either the exact log2 value or min_int. It's been an issue for some computations we make, so I'm changing this behaviour.

PDLL builtins: Allow float log2 to return even if the log2 is not exact

---

mlir/lib/Dialect/Math/Transforms/ExpandPatterns.cpp
mlir/test/Dialect/Math/expand-math.mlir

This reconciles the expansion of math.rsqrt with upstream after code review changes.

Reconcile math.rsqrt expansion with upstream

---

mlir/docs/Dialects/emitc.md
mlir/include/mlir/Conversion/ArithToEmitC/ArithToEmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/include/mlir/Dialect/EmitC/IR/EmitCTypes.td
mlir/include/mlir/Dialect/EmitC/Transforms/TypeConversions.h
mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/lib/Conversion/ArithToEmitC/ArithToEmitCPass.cpp
mlir/lib/Conversion/FuncToEmitC/FuncToEmitCPass.cpp
mlir/lib/Conversion/MemRefToEmitC/MemRefToEmitCPass.cpp
mlir/lib/Conversion/SCFToEmitC/SCFToEmitC.cpp
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/lib/Dialect/EmitC/Transforms/TypeConversions.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir
mlir/test/Dialect/EmitC/invalid_ops.mlir
mlir/test/Dialect/EmitC/invalid_types.mlir
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Dialect/EmitC/types.mlir
mlir/test/Target/Cpp/types.mlir

When upstreaming our fork's changes to the main LLVM, we had to introduce minor changes to the code that weren't backported into our fork. This commit does this backport to make bumping easier.

Reconcile EmitC changes with upstream

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg.mlir

TOSA Cast ops accept unsigned integers as input; when widening such types, they must not be sign-extended.
This commit also fixes the naming of one test that appeared to be wrong (the test uses i8 instead of ui8).

[FXML-4819] Lower tosa.cast uiX -> (us)?iY to extui

---

mlir/include/mlir/Dialect/PDL/IR/Builtins.h
mlir/lib/Dialect/PDL/IR/Builtins.cpp
mlir/lib/Tools/PDLL/Parser/Lexer.cpp
mlir/lib/Tools/PDLL/Parser/Lexer.h
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/lib/Tools/mlir-pdll-lsp-server/PDLLServer.cpp
mlir/test/lib/Tools/PDLL/TestPDLL.pdll
mlir/test/mlir-pdll-lsp-server/completion.test
mlir/test/mlir-pdll/CodeGen/MLIR/expr.pdll
mlir/test/mlir-pdll/Integration/test-pdll.mlir
mlir/test/mlir-pdll/Parser/expr-failure.pdll
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/unittests/Dialect/PDL/BuiltinTest.cpp

Allows to write
```
Pattern TestEquals {
let op = op<test.op> {val = val : Attr};
val == attr<"4 : i32">;
replace op with op<test.success>;
}
```.
In addition, this PR has a commit to exclude __builtins from code completion in LSP.

PDLL: Add equals operator

---

mlir/include/mlir/Dialect/PDL/IR/Builtins.h
mlir/lib/Dialect/PDL/IR/Builtins.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/CodeGen/MLIR/expr.pdll
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/unittests/Dialect/PDL/BuiltinTest.cpp

Instead of using native calls to create array/dict attributes, use the pdl.attribute op.

PDLL: Create array/dict attributes more directly

---

mlir/docs/Dialects/emitc.md
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/invalid_types.mlir
mlir/test/Dialect/EmitC/types.mlir

This is allowed as a GCC extension, see https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html.
It's helpful when coming from tensors with zero size dimensions to make the lowering code more uniform.

EmitC: Allow arrays of size zero

---

.github/workflows/pr-code-format.yml

This is a hotfix using commit f6c87be1 from upstream to get CI to pass on `feature/fused-ops` before carrying on further bumping. One review will be enough.
The recent change to split the PR code formatting job accidentally misspelled the repository field when specifying the repository to fetch the code formatting utils from. This patch fixes the spelling so that the job does not throw a warning and clones the tools from the specified repository.

[Github] Fix typo in PR code formatting job

---

.github/workflows/pr-code-format.yml

This PR moves the code checking step from merging to `main` to PRs targeting `feature/fused-ops`. Since we're using `feature/fused-ops` as our main branch in this repo, we'll check code formatting of PRs that target `feature/fused-ops` instead of `main`.
This PR will fix the issue we're currently having with CI (failing code formatting step after merging into `feature/fused-ops`): since our `main` is late with respect to LLVM's, the script's version in `main` is too old and is missing one argument that our branch `feature/fused-ops` wants.

Run code formatter on PRs targeting feature/fused-ops

---

mlir/lib/Dialect/EmitC/IR/FunctionOpAssembly.cpp
mlir/test/Dialect/EmitC/func.mlir

The EmitC function assembly printer failed to print "ref" next to reference arguments, and the test wouldn't pick it up because it wouldn't run FileCheck. This PR gets all of that fixed.

[FXML-4791] Hotfix to function assembly printer

---

mlir/lib/Dialect/EmitC/IR/EmitC.cpp

Unfortunately, we can't test this other than with a C++ test, as the MLIR parser will catch the error on its own before we reach `emitc::ArrayType::verify()`.

EmitC array type : verify dynamic shape before negative size

---

mlir/include/mlir/Conversion/Passes.td
mlir/include/mlir/Conversion/UBToEmitC/UBToEmitC.h
mlir/lib/Conversion/UBToEmitC/UBToEmitC.cpp
mlir/test/Conversion/UBToEmitC/convert-ub-to-emitc-no-init.mlir
mlir/test/Conversion/UBToEmitC/convert-ub-to-emitc.mlir

This changes the behavior of `ub-to-emitc` to initialize variables to 42 by default, and adds an option to to skip this initialization.

[FXML-5071] Add option to initialize UB.poison variables

---

mlir/include/mlir/Dialect/Affine/Utils.h
mlir/lib/Dialect/Affine/Utils/Utils.cpp
mlir/lib/Dialect/MemRef/Transforms/NormalizeMemRefs.cpp
mlir/test/Dialect/MemRef/normalize-memrefs.mlir

The pass was only handling memref.alloc,
and this extends it to also handle memref.alloca.

normalize-memrefs: Normalize memref.alloca

---

mlir/lib/Conversion/SCFToEmitC/SCFToEmitC.cpp

The lowering of `scf.for` ops uses the non-lowered operands, which breaks when these operands have undergone EmitC lowering.

[FXML-5083] SCFToEmitC: use already lowered operands

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Dialect/EmitC/invalid_ops.mlir
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Target/Cpp/verbatim.mlir

Allows to print pragmas that refer to arguments or local variables.
E.g. `emitc.verbatim "#pragma abc var={}" %arg0 : !emitc.ptr<i32>` is printed as `#pragma abc var=v1`

emitc: Add fmtArgs to verbatim

---

mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Target/Cpp/verbatim.mlir

There was code to suppress printing semicolons after emitc.verbatim in the function that emits a function body, but then it would still print `#pragma;` when the `emitc.verbatim "#pragma"` was within a loop body.
I moved that code into the general printOperation() function, so it applies to emitc.verbatim independent of what the parent op is.

Don't print semicolon after emitc.verbatim within emitc.for

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/test/Dialect/EmitC/invalid_ops.mlir
mlir/test/Dialect/EmitC/ops.mlir
mlir/test/Target/Cpp/verbatim.mlir

With the previous parsing, it would interpret
```
emitc.verbatim "#endif // PL_USE_XRT"
%4 = "emitc.constant"() <{value = 1 : i32}> : () -> i32
```
as if
```
emitc.verbatim "#endif // PL_USE_XRT" %4
= "emitc.constant"() <{value = 1 : i32}> : () -> i32
```
and then complain that it expected a `:` after the `%4`.
Fix this by introducing a `args` keyword to distinguish the case where the veratim has args from the case where the next operation starts.

Fix verbatim parsing to be unambiguous

---

mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp
mlir/test/Conversion/TosaToLinalg/tosa-to-linalg.mlir

When deciding whether to emit a map like
`#map = affine_map<(d0, d1, d2, d3) -> (0, d1, d2, d3)>` or `#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>` for an operand of a linalg.generic when lowering element-wise TOSA ops, prefer the latter unless broadcasting of the operand is really needed.
This helps later transformations which often require the affine map to be a projected permuatation, which only the latter is.

TosaToLinalg: Prefer to emit identity maps

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/include/mlir/Target/Cpp/CppEmitter.h
mlir/lib/Target/Cpp/TranslateRegistration.cpp
mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Target/Cpp/tu.mlir

A `emitc.tu` represents a translation unit that can be emitted
into a single C++ file.
`mlir-translate` emits only the translation unit selected via
the `-translation-unit-id=id` flag. By default, no translation units are
emitted.
Example:
```mlir
emitc.tu "main" {
emitc.func @func_one() {
emitc.return
}
}
```

Add emitc.tu

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.td

`#include` make sense everywhere, and in particular we need to allow them inside a `emitc.tu`. But sometimes we might even want to have an `#include` in a function body.

emitc.include: don't require the parent to be a ModuleOp

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
mlir/lib/Dialect/EmitC/IR/EmitC.cpp

The auto-generated builder created an emitc.tu that had an empty region. This is a bit cumbersome to work with, as you would always manually needed to create a block in it.
Do what ModuleOp::build does and always create that block.
Also accept StringRef as argument for id instead of requiring a StringAttr.

emitc.tu: Automatically create block for body

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize_with_debuginfo.mlir

Issue: when folding two reshapes, we were losing the location of the first one.
PS.: there are more operations with a similar issue, but let's address them later.

fix: fuse locations of double reshapes when folding.

---

mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.td
mlir/include/mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.td
mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h
mlir/include/mlir/Dialect/Linalg/Utils/Utils.h
mlir/include/mlir/Dialect/SCF/Transforms/TileUsingInterface.h
mlir/include/mlir/Dialect/Tensor/Transforms/Transforms.h
mlir/include/mlir/Interfaces/TilingInterface.h
mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
mlir/lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp
mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp
mlir/lib/Dialect/Linalg/Transforms/TilingInterfaceImpl.cpp
mlir/lib/Dialect/Linalg/Transforms/WinogradConv2D.cpp
mlir/lib/Dialect/Linalg/Utils/Utils.cpp
mlir/lib/Dialect/SCF/Transforms/TileUsingInterface.cpp
mlir/lib/Dialect/Tensor/IR/TensorTilingInterfaceImpl.cpp
mlir/lib/Dialect/Tensor/Transforms/ReshapePatterns.cpp
mlir/test/Dialect/Linalg/transform-op-fuse.mlir
mlir/test/Dialect/Linalg/transform-tile-and-winograd-rewrite.mlir
mlir/test/Dialect/Linalg/transform-tile-winograd.mlir
mlir/test/Dialect/Tensor/bubble-reshapes.mlir
mlir/test/Interfaces/TilingInterface/tile-and-fuse-consumer.mlir
mlir/test/Interfaces/TilingInterface/tile-and-fuse-using-interface.mlir
mlir/test/lib/Dialect/Tensor/TestTensorTransforms.cpp
mlir/test/lib/Interfaces/TilingInterface/TestTilingInterfaceTransformOps.cpp

The important ones are 22fcd3e1d2c4c623fb46d0254b1d67f606891e30 and a8317e1f17bad0640a2d07795521b8eee60c9829. The others are there to avoid merge conflicts.

Backport various improvements to fusion from upstream

---

mlir/lib/Transforms/CSE.cpp
mlir/test/Transforms/cse_with_locations.mlir

We lose location of the `op to be replaced` when CSE'ing. This is important so that we know what got optimized in the IR. Otherwise, such information is lost.
This should fix this.

feat: improve CSE by fusing locations when replacing one op for the other.

---

mlir/lib/Target/Cpp/TranslateToCpp.cpp
mlir/test/Target/Cpp/tu.mlir

I don't know how to test this, as there seems to be no way in FileCheck to check that either the output doesn't start with a newline or doesn't end with a newline.

emitc: Do not add newlines after ModuleOp, TranslationUnitOp

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir

`arith.fptoui %arg0 : f32 to i16` was lowered to
```
%0 = emitc.cast %arg0 : f32 to ui32
emitc.cast %0 : ui32 to i16
```
and is now lowered to
```
%0 = emitc.cast %arg0 : f32 to ui16
emitc.cast %0 : ui16 to i16
```

arith-to-emitc: Fix lowering of fptoui

---

mlir/include/mlir/Dialect/EmitC/IR/EmitC.h
mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/lib/Dialect/EmitC/IR/EmitC.cpp

Ensure that floating point ops allow their target type to be emitc.opaque.

ArithToEmitC: Support using opaque types for floating point

---

mlir/include/mlir/IR/AffineExpr.h
mlir/include/mlir/IR/AffineMap.h
mlir/lib/Dialect/Linalg/Utils/Utils.cpp
mlir/lib/IR/AffineExpr.cpp
mlir/lib/IR/AffineMap.cpp
mlir/test/Dialect/Linalg/tile-tensors.mlir

`computeSliceParameters` maps the loop range (given by lower bounds `lbs` and upper bounds `ubs`) into the operand tensor to compute the input slices that contains all indexed values.
The computation currently assumes that the affine expressions to map from loop iteration domain to tensor domain are monotonic, and use that information by just evaluating those at `lbs` and `ubs` to obtain the slice o the operand tensor.
For non-monotonic expressions, the maximum and minimum values might not be at the boundaries.
Detect that case, and then use the full slice to be safe.
Fixes #111830
If shapes are static, we could be cleverer: sometimes we can prove that even though the affine expression is not monotonic in itself, it is monotonic on the range `(lbs, ubs)`. For example when the affine …

computeSliceParameters: use full slice if affine exprs are non-monotonic

---

mlir/include/mlir/Dialect/Affine/Utils.h
mlir/lib/Dialect/Affine/Utils/Utils.cpp

Extend affine::normalizeMemRef to return FailureOr<AllocLikeOp>, where AllocLikeOp is the normalized `memref.alloca` or `memref.alloc`.

Extend affine::normalizeMemRef to return FailureOr<AllocLikeOp>

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize.mlir

If we have a sequence of casts that first go to a bigger (f32) and then to a strictly smaller type (bf16), we can fold this and avoid the intermediate bigger type (f32).

TOSA: fold cast-to-bf16(cast-to-f32(x)) -> cast-to-bf16(x)

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize.mlir

The fold() of the concat had two issues:
a) It would fold `concat (tensor<0x2>, tensor<0x4>), axis=1 -> tensor<0x6>` into `concat ()` (no operands) based on the observation that both operands have zero elements. This is invalid as concat needs to have at least one operand.
b) After that fix, it would fold `concat (tensor<0x2>, tensor<0x4>), axis=1 -> tensor<0x6>` int `concat (tensor<0x4>), axis=1 -> tensor<0x6>`. This is also invalid; even though the concat still produces the same number of elements (= none), shape relations are not corret (0x4 input, but 0x6 output).
I fixed that by only removing operands from the concat when
- the operand has zero dim on the concatenation axis (i.e. it doesn't contribute to the result shape)
- there is at least one operand left after removing

TOSA: concat: fix canonicalization that would result in concat with no operands

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
mlir/lib/Dialect/EmitC/IR/EmitC.cpp
mlir/test/Dialect/EmitC/ops.mlir

I can unfortunately not really test this since there is not type conversion from float to an opaque type.
We might want some made-for-testing-purposes opaque type conversions (in a separate PR) to ensure that opaque type conversions are handled properly in all upstream lowerings.

EmitC: Allow casts between opaque and float types

---

.github/workflows/llvm-project-tests.yml

We use the docker image from upstream (`ghcr.io/llvm/ci-ubuntu-22.04:latest`), which changed recently to use a non-root users (b86a22aa3915).
Switch user back to `root`.

Fix for upstream change in docker container

---

mlir/test/lit.cfg.py

This PR exchanges the used Python executable inside the MLIR LIT test suite, when the build is configured for utilizing ASan. The executable is replaced with a shim script, which preloads the necessary ASan shared object file as it did before, but additionally exhibits two benefits:
1. Provide full support for LLVM's test utils like `not`, which are prepended to the original statement containing the `LD_PRELOAD` env definition. Having environment definitions in the middle of a command line is syntactically illegal.
2. Mitigate issues with LIT's internal shell that puts single quotes around the environment definition, which leads to malformed command lines: `LD_PRELOAD=$(/usr/bin/clang++-17' '-print-file-name=libclang_rt.asan-x86_64.so)' python (...)`
- The problem might be circumvented by …

asan: replace used python in mlir lit.cfg with shim script

---

mlir/lib/Dialect/Linalg/Utils/Utils.cpp
mlir/test/Dialect/Linalg/tile-offset.mlir

For affine maps where `m(0) != 0`,
like `affine_map<(d0) -> (d0 + 3)` in
```
%generic = linalg.generic
{indexing_maps = [affine_map<(d0) -> (d0 + 3)>,
affine_map<(d0) -> (d0)>],
iterator_types = ["parallel"]} ins(%arg0: tensor<9xf32>) outs(%empty : tensor<6xf32>) {
^bb0(%in : f32, %out: f32):
linalg.yield %in : f32
} -> tensor<6xf32>
```
tiling currently computes the wrong slice offsets. When tiling above example with a size of 3, it would compute
```
scf.for %i = ...
%slice = tensor.extract_slice %arg0[%i + 3] [6] [1]
linalg.generic
{indexing_maps = [affine_map<(d0) -> (d0 + 3)>,
affine_map<(d0) -> (d0)>],
iterator_types = ["parallel"]} ins(%slice: tensor<6xf32>)
```
and thus apply the `+3` twice (once in the extract slice and a second time in the linalg.generic).
This PR fixes this to …

computeSliceParameters: Fix offset when m(0) != 0

---

mlir/include/mlir/Transforms/Passes.h
mlir/lib/Transforms/ControlFlowSink.cpp

Many places expect on `linalg.index` ops directly nested within `linalg.generic`, so it seems easier to just restrict the `control-flow-sink` pass from moving `linalg.index` ops.
To achieve that, I expose the `shouldMoveIntoRegion` option on the pass while keeping the default behavior the same.

[MLIR] control-flow-sink: Allow to configure shouldMoveIntoRegion

---

mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.td
mlir/lib/Dialect/Linalg/IR/LinalgInterfaces.cpp
mlir/lib/Dialect/Linalg/Transforms/ConstantFold.cpp

`computeStaticLoopSizes()` is functionally identical to `getStaticLoopRanges()`. Replace all uses of `computeStaticLoopSizes()` by `getStaticLoopRanges()` and remove the former.

Cherry-pick "[mlir][linalg] Remove computeStaticLoopSizes"

---

mlir/lib/Analysis/AffineExprBounds.cpp
mlir/test/Analysis/test-affine-expr-bounds.mlir

`inferRemS` is a signed mod. We want to infer with signed bounds (so `inferRemU` is not suitable [1]), but return a result between 0 and (mod factor)-1 (a true Euclidean division remainder).
[1] `signedRemU` for `affine_map<(d0) -> (d0 mod 5)>, lbs = [-4], ubs = [-2]` would give `expr_lb = [2], expr_ub = [4]` as a result.

Ensure 0 <= x mod N < N semantics

---

mlir/test/get_darwin_real_python.py
mlir/test/lit.cfg.py

[AutoBump] Merge with fixes of beff2bac (Nov 22) (14)

---

mlir/include/mlir/Dialect/PDL/IR/Builtins.h
mlir/lib/Dialect/PDL/IR/Builtins.cpp
mlir/lib/Tools/PDLL/Parser/Parser.cpp
mlir/test/mlir-pdll/CodeGen/MLIR/expr.pdll
mlir/test/mlir-pdll/Parser/expr-failure.pdll
mlir/test/mlir-pdll/Parser/expr.pdll
mlir/unittests/Dialect/PDL/BuiltinTest.cpp

In PDLL the syntax `let array = ["attr1", "attr2"];` is only usable in rewrite section, but not in constraint section of a pattern.
This PR add the parsing of this syntax also in the constraint section of a pattern.
Also, the empty array `[]` was considered as a parsing error, this PR fix this little parsing issue.

feat: allow arrayAttr parsing in constraint

---

mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp

Use the emitc-provided function to check the types instead of checking for float types, as the other arith lowering do.

Check valid emitc float/opaque types, not float

---

mlir/cmake/modules/AddMLIRPython.cmake

Otherwise we get hundreds of warnings during cmake.

cmake: Use old CMP0175 policy

---

mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp
mlir/test/Dialect/Tosa/canonicalize.mlir

I plan to upstream this in the future

Add support for folding tosa.slice with tosa.slice

---

mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.td
mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
mlir/test/Dialect/Linalg/tile-softmax.mlir

Tiling existed for the SoftMax op, but tile-and-fuse was not implemented. This adds the required interface function. It essentially creates a tile of iterations and a tile of the input, from a tile of the output. 
How SoftMax has been implemented makes it that tiling from the output is the same as that for tiling the "iteration domain": that domain corresponds to the input/output tensor, whereas once decomposed, linalg.generics with extra dimensions appear. The tensor dimension over which the reductions happen (in this invisible extra dimension) is considered a reduction iteration dimension, which indicates it shouldn't be tiled.

Provide tile-and-fuse for SoftMax

---

mlir/include/mlir/IR/BuiltinAttributes.h
mlir/lib/IR/BuiltinAttributes.cpp
mlir/unittests/IR/AttributeTest.cpp

Reverts Xilinx/llvm-project#568

Revert "Allow to use the DenseElementsAttr get methods to be used with types …"
